@startuml
enum "IntegType" as C_0003544794305486865442
enum C_0003544794305486865442 {
outside
insde
}
class "RegulatorPID" as C_0000332654898198268485
class C_0000332654898198268485 {
+RegulatorPID(double k, double T_i = 0.0, double T_d = 0.0, IntegType integration_type = IntegType::outside) : void
..
+getIntegrationType() : IntegType
+getK() : double
+getT_d() : double
+getT_i() : double
+reset() : void
+resetDerrivativePart() : void
+resetIntegrationPart() : void
+setIntegrationType(IntegType integ_type) : void
+setK(double k) : void
+setT_d(double T_d) : void
+setT_i(double T_i) : void
+tick(double e_i) : double
__
-T_d : double
-T_i : double
-integration_type : IntegType
-k : double
-previous_e : double
-sum_of_e_inside_integ : double
-sum_of_e_outside_integ : double
}
class "std::pair<bool,const char *>" as C_0014553804139211016925
class C_0014553804139211016925 {
__
}
class "std::pair<double,double>" as C_0016436472329008043786
class C_0016436472329008043786 {
__
}
class "std::vector<double>" as C_0001104664960286800752
class C_0001104664960286800752 {
__
}
class "std::deque<double>" as C_0005615096916452297607
class C_0005615096916452297607 {
__
}
class "std::function<void(TickData)>" as C_0003871390626336603026
class C_0003871390626336603026 {
__
}
class "std::map<qreal,uint16_t>" as C_0001997022298513289013
class C_0001997022298513289013 {
__
}
class "Test" as C_0002626979548338364165
class C_0002626979548338364165 {
+Test() = deleted : void
..
{static} -TEST_ARX_nietypowe_AB() : std::pair<bool,const char *>
{static} -TEST_ARX_ustawienie_K() : std::pair<bool,const char *>
{static} -TEST_ARX_zaklocenia() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_100_procent() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_10_procent() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_50_procent() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_bias() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_zmiana_amplitudy() : std::pair<bool,const char *>
{static} -TEST_Generator_Prostokatny_zmiana_okresu() : std::pair<bool,const char *>
{static} -TEST_Generator_Sinusoidalny() : std::pair<bool,const char *>
{static} -TEST_Generator_Sinusoidalny_bias() : std::pair<bool,const char *>
{static} -TEST_Generator_Sinusoidalny_zmiana_amplitudy() : std::pair<bool,const char *>
{static} -TEST_Generator_Sinusoidalny_zmiana_okresu() : std::pair<bool,const char *>
{static} -TEST_ListWithExtremes_poprawne_dzialanie() : std::pair<bool,const char *>
{static} -TEST_PID_czlon_D_przyspiesza_regulacje() : std::pair<bool,const char *>
{static} -TEST_PID_czlon_P_regulacja_odwrotna() : std::pair<bool,const char *>
{static} -TEST_State_czy_jest_signletonem() : std::pair<bool,const char *>
{static} -TEST_State_zapis_i_odczyt_z_pliku() : std::pair<bool,const char *>
{static} -porownajZTolerancja(const double a, const double b, const double EPS = 1e-4) : bool
{static} +wykonajTesty() : void
__
}
abstract "Generator" as C_0015873013232297291266
abstract C_0015873013232297291266 {
+Generator() : void
..
#advanceClockAndReturn(double) : double
+getAmplitude() : double
+getBias() : double
+getSamplesPerCycle() : uint16_t
+resetClock() : void
+setAmplitude(double amplitude) : void
+setBias(double bias) : void
+setSamplesPerCycle(uint16_t samples_per_cycle) : void
{abstract} +tick() = 0 : double
__
#amplitude : double
#bias : double
#internal_clock : uint16_t
#samples_per_cycle : uint16_t
}
class "GeneratorSinusoida" as C_0006611994892758867615
class C_0006611994892758867615 {
+GeneratorSinusoida() : void
..
+tick() : double
__
}
class "ARX" as C_0018043015608687228134
class C_0018043015608687228134 {
+ARX(std::vector<double> && a, std::vector<double> && b, uint16_t k = 1, double standard_deviation = 0.0) : void
..
-applyLimits(std::pair<double,double> & limits, double value) : double
+disableLimits() : void
+enableLimits() : void
+getA() : const std::vector<double>
+getB() : const std::vector<double>
-getGaussianDistribValue() : double
+getInputLimits() : const std::pair<double,double> &
+getK() : double
+getOutputLimits() : const std::pair<double,double> &
+getStandardDeviation() : double
+reset() : void
+setAB(std::vector<double> a, std::vector<double> b) : void
+setInputLimits(double low, double high) : void
+setK(uint16_t k) : void
+setOutputLimits(double low, double high) : void
+setStandardDeviation(double standard_deviation) : void
+tick(double u) : double
__
-a : std::vector<double>
-b : std::vector<double>
-input_limits : std::pair<double,double>
-k : uint16_t
-limits_active : bool
-output_limits : std::pair<double,double>
-standard_deviation : double
-u_i : std::deque<double>
-y_i : std::deque<double>
}
class "TickData" as C_0016418138640912755596
class C_0016418138640912755596 {
__
+sterowanie : double
+uchyb : double
+wartosc_regulowana : double
+wartosc_zadana : double
}
class "UAR" as C_0007070034700002168771
class C_0007070034700002168771 {
+UAR(ARX && arx, RegulatorPID && pid) : void
+UAR(ARX & arx, RegulatorPID & pid) : void
..
+getARX() : ARX &
+getRegulatorPID() : RegulatorPID &
+resetAll() : void
+tick(double input) : double
+tick_more_info(double input) : TickData
__
-arx : ARX
-pid : RegulatorPID
-previous_y_i : double
}
class "Ui::MainWindow" as C_0005461363864585996070
class C_0005461363864585996070 {
__
}
class "Ui::DialogArx" as C_0001241395230117963560
class C_0001241395230117963560 {
__
}
class "QList<QPointF>" as C_0005180472283857981683
class C_0005180472283857981683 {
__
}
class "MainWindow" as C_0002900986228388971956
class C_0002900986228388971956 {
+MainWindow(QWidget * parent = nullptr) : void
+~MainWindow() : void
..
+addToPlots(TickData tick_data) : void
+metaObject() const : const QMetaObject *
-on_checkBoxOgraniczenia_checkStateChanged(const Qt::CheckState & arg1) : void
-on_comboBox_generator_typ_currentTextChanged(const QString & arg1) : void
-on_doubleSpinBox_generator_amplituda_editingFinished() : void
-on_doubleSpinBox_generator_amplituda_valueChanged(double arg1) : void
-on_doubleSpinBox_pid_Td_editingFinished() : void
-on_doubleSpinBox_pid_Td_valueChanged(double arg1) : void
-on_doubleSpinBox_pid_Ti_editingFinished() : void
-on_doubleSpinBox_pid_Ti_valueChanged(double arg1) : void
-on_doubleSpinBox_pid_k_editingFinished() : void
-on_doubleSpinBox_pid_k_valueChanged(double arg1) : void
-on_horizontalSlider_generator_okres_sliderReleased() : void
-on_horizontalSlider_generator_okres_valueChanged(int value) : void
-on_horizontalSlider_generator_wypelnienie_sliderReleased() : void
-on_horizontalSlider_generator_wypelnienie_valueChanged(int value) : void
-on_horizontalSlider_pid_Td_sliderReleased() : void
-on_horizontalSlider_pid_Td_valueChanged(int value) : void
-on_horizontalSlider_pid_Ti_sliderReleased() : void
-on_horizontalSlider_pid_Ti_valueChanged(int value) : void
-on_horizontalSlider_pid_k_sliderReleased() : void
-on_horizontalSlider_pid_k_valueChanged(int value) : void
-on_horizontalSlider_symulacja_interwal_sliderReleased() : void
-on_horizontalSlider_symulacja_interwal_valueChanged(int value) : void
-on_horizontalSlider_symulacja_okno_obserwacji_sliderReleased() : void
-on_horizontalSlider_symulacja_okno_obserwacji_valueChanged(int value) : void
-on_pushButton_dostosuj_parametry_clicked() : void
-on_pushButton_reset_pam_calk_clicked() : void
-on_pushButton_reset_pam_roz_clicked() : void
-on_pushButton_symulacja_reset_clicked() : void
-on_pushButton_symulacja_star_stop_released() : void
-on_radioButton_stala_calkowania_pod_clicked() : void
-on_radioButton_stala_calkowania_przed_clicked() : void
-on_spinBox_generator_okres_editingFinished() : void
-on_spinBox_generator_okres_valueChanged(int arg1) : void
-on_spinBox_generator_wypelnienie_editingFinished() : void
-on_spinBox_generator_wypelnienie_valueChanged(int arg1) : void
-on_spinBox_symulacja_interwal_editingFinished() : void
-on_spinBox_symulacja_interwal_valueChanged(int arg1) : void
-on_spinBox_symulacja_okno_obserwacji_editingFinished() : void
-on_spinBox_symulacja_okno_obserwacji_valueChanged(int arg1) : void
-on_verticalSlider_generator_amplituda_sliderMoved(int position) : void
-on_verticalSlider_generator_amplituda_sliderReleased() : void
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
-recalculate_generator_period() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-chart_sterowanie : QChart *
-chart_uchyb : QChart *
-chart_wartosc_zadana_i_regulowana : QChart *
-chart_wszystko : QChart *
-debug_last_time : int
-debug_timer : QElapsedTimer
-lista_sterowanie : QList<QPointF> *
-lista_uchyb : QList<QPointF> *
-lista_wartosc_regulowana : QList<QPointF> *
-lista_wartosc_zadana : QList<QPointF> *
-miliseconds_of_simulation : qint64
-samples_count : uint32_t
{static} +staticMetaObject : const QMetaObject
-ui : Ui::MainWindow *
}
class "MainWindow::QPrivateSignal" as C_0013559316693802428772
class C_0013559316693802428772 {
+QPrivateSignal() constexpr = default : void
__
}
class "GeneratorProstokatny" as C_0002207342585688024720
class C_0002207342585688024720 {
+GeneratorProstokatny() : void
..
+getDutyCycle() : double
+setDutyCycle(double duty_cycle) : void
+tick() : double
__
-duty_cycle : double
}
class "State" as C_0012548033600169640822
class C_0012548033600169640822 {
-State(const State &) = deleted : void
-State(UAR &&) : void
-~State() : void
..
-operator=(const State &) = deleted : State &
..
+getARXCoefficientsA() : const std::vector<double>
+getARXCoefficientsB() : const std::vector<double>
+getARXInputLimits() : const std::pair<double,double> &
+getARXNoiseStandardDeviation() : double
+getARXOutputLimits() : const std::pair<double,double> &
+getARXTransportDelay() : uint16_t
+getGeneneratorPeriodJumpMS() : uint8_t
+getGenerator() : TypGeneratora
{static} +getInstance() : State &
+getSimmulationIntervalMS() : uint32_t
+getSimmulationRunning() : bool
+metaObject() const : const QMetaObject *
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
+readFromFile() : void
+resetARX() : void
+resetGenerator() : void
+resetPIDDerrivative() : void
+resetPIDIntegration() : void
+resetSimmulation() : void
+saveToFile() : void
+setARXCoefficients(std::vector<double> a, std::vector<double> b) : void
+setARXInputLimits(double low, double high) : void
+setARXLimitsEnabled(bool enabled) : void
+setARXNoiseStandardDeviation(double standard_deviation) : void
+setARXOutputLimits(double low, double high) : void
+setARXTransportDelay(uint16_t k) : void
+setGeneneratorAmplitude(const double & amplitude) : void
+setGeneneratorDutyCycle(const double & duty_cycle) : void
+setGeneneratorPeriodMS(uint32_t period) : void
+setGenerator(TypGeneratora type) : void
+setOutputCallback(const std::function<void (TickData)> callback) : void
+setPIDDerrivative(double T_d) : void
+setPIDIntegration(double T_i) : void
+setPIDIntegrationType(IntegType integration_type) : void
+setPIDProportional(double k) : void
+setSimmulationIntervalMS(uint32_t interval) : void
+setSimmulationRunning(bool simmulation_running) : void
+tick() : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
__
-choosen_type : TypGeneratora
-gen_pros : GeneratorProstokatny
-gen_sin : GeneratorSinusoida
-simmulation_running : bool
-simmulation_timer : QTimer *
{static} +staticMetaObject : const QMetaObject
-tick_callback : std::function<void (TickData)>
-uar : UAR
}
class "State::QPrivateSignal" as C_0009647332571105013514
class C_0009647332571105013514 {
+QPrivateSignal() constexpr = default : void
__
}
enum "State::TypGeneratora" as C_0011773683672513422965
enum C_0011773683672513422965 {
Sinusoidalny
Prostokatny
Reczny
}
class "Ui_MainWindow" as C_0008416453855301937033
class C_0008416453855301937033 {
+retranslateUi(QMainWindow * MainWindow) : void
+setupUi(QMainWindow * MainWindow) : void
__
+actionMINECRAAAAAAFT : QAction *
+actioneksport_wykres_w : QAction *
+actionpraca_wielow_tkowa : QAction *
+actionwczytaj_ustawienia : QAction *
+actionwy_wietlaj_wykresy_w_tej_samej_skali : QAction *
+actionzapisz_ustawienia : QAction *
+actionzatwierdzaj_zmiany_natychmiast : QAction *
+centralwidget : QWidget *
+checkBoxOgraniczenia : QCheckBox *
+comboBox_generator_typ : QComboBox *
+doubleSpinBox_generator_amplituda : QDoubleSpinBox *
+doubleSpinBox_pid_Td : QDoubleSpinBox *
+doubleSpinBox_pid_Ti : QDoubleSpinBox *
+doubleSpinBox_pid_k : QDoubleSpinBox *
+groupBox : QGroupBox *
+groupBox_2 : QGroupBox *
+groupBox_3 : QGroupBox *
+groupBox_4 : QGroupBox *
+horizontalLayout : QHBoxLayout *
+horizontalLayoutWidget_9 : QWidget *
+horizontalLayout_10 : QHBoxLayout *
+horizontalLayout_11 : QHBoxLayout *
+horizontalLayout_12 : QHBoxLayout *
+horizontalLayout_13 : QHBoxLayout *
+horizontalLayout_14 : QHBoxLayout *
+horizontalLayout_15 : QHBoxLayout *
+horizontalLayout_2 : QHBoxLayout *
+horizontalLayout_3 : QHBoxLayout *
+horizontalLayout_4 : QHBoxLayout *
+horizontalLayout_5 : QHBoxLayout *
+horizontalLayout_6 : QHBoxLayout *
+horizontalLayout_7 : QHBoxLayout *
+horizontalLayout_8 : QHBoxLayout *
+horizontalLayout_9 : QHBoxLayout *
+horizontalSlider_generator_okres : QSlider *
+horizontalSlider_generator_wypelnienie : QSlider *
+horizontalSlider_pid_Td : QSlider *
+horizontalSlider_pid_Ti : QSlider *
+horizontalSlider_pid_k : QSlider *
+horizontalSlider_symulacja_interwal : QSlider *
+horizontalSlider_symulacja_okno_obserwacji : QSlider *
+horizontalSpacer : QSpacerItem *
+horizontalSpacer_2 : QSpacerItem *
+horizontalSpacer_3 : QSpacerItem *
+horizontalSpacer_4 : QSpacerItem *
+horizontalSpacer_5 : QSpacerItem *
+label : QLabel *
+label_2 : QLabel *
+label_3 : QLabel *
+label_4 : QLabel *
+label_5 : QLabel *
+label_6 : QLabel *
+label_7 : QLabel *
+label_8 : QLabel *
+label_9 : QLabel *
+menubar : QMenuBar *
+menuplik : QMenu *
+menuzachowanie : QMenu *
+pushButton_dostosuj_parametry : QPushButton *
+pushButton_reset_pam_calk : QPushButton *
+pushButton_reset_pam_roz : QPushButton *
+pushButton_symulacja_reset : QPushButton *
+pushButton_symulacja_star_stop : QPushButton *
+radioButton_stala_calkowania_pod : QRadioButton *
+radioButton_stala_calkowania_przed : QRadioButton *
+spinBox_generator_okres : QSpinBox *
+spinBox_generator_wypelnienie : QSpinBox *
+spinBox_symulacja_interwal : QSpinBox *
+spinBox_symulacja_okno_obserwacji : QSpinBox *
+statusbar : QStatusBar *
+toolBar : QToolBar *
+verticalLayout : QVBoxLayout *
+verticalLayout_4 : QVBoxLayout *
+verticalLayout_5 : QVBoxLayout *
+verticalLayout_6 : QVBoxLayout *
+verticalLayout_7 : QVBoxLayout *
+verticalLayout_8 : QVBoxLayout *
+verticalLayout_9 : QVBoxLayout *
+verticalLayout_wykresy : QVBoxLayout *
+verticalSlider_generator_amplituda : QSlider *
+verticalSpacer : QSpacerItem *
}
class "DialogArx" as C_0004934292542202437282
class C_0004934292542202437282 {
+DialogArx(QWidget * parent = nullptr) : void
+~DialogArx() : void
..
-aktualizuj_widok(double odchylenie) : void
+metaObject() const : const QMetaObject *
-on_zaklocenie_suwak_valueChanged(int value) : void
-on_zaklocenie_wartosc_valueChanged(int arg1) : void
{static} -qt_create_metaobjectdata<typename>() constexpr : auto
+qt_metacall(QMetaObject::Call, int, void **) : int
+qt_metacast(const char *) : void *
{static} -qt_static_metacall(QObject *, QMetaObject::Call, int, void **) : void
{static} +tr(const char * s, const char * c = nullptr, int n = -1) : QString
-ustaw_wykres() : void
__
-LICZBA_PROBEK : const int
-axisX : QValueAxis *
-axisY : QValueAxis *
-chart_zaklocenia : QChart *
-odchylenie : double
-seria_zaklocen : QLineSeries *
{static} +staticMetaObject : const QMetaObject
-ui : Ui::DialogArx *
}
class "DialogArx::QPrivateSignal" as C_0018037893356612265046
class C_0018037893356612265046 {
+QPrivateSignal() constexpr = default : void
__
}
class "ListWithExtremes" as C_0009968107519566864188
class C_0009968107519566864188 {
+ListWithExtremes() : void
..
+appendLastValue(QPointF new_point) : void
+deleteFirstValue() : void
+getList() : QList<QPointF> *
+getMaxValue() : qreal
+getMinValue() : qreal
__
-list : QList<QPointF>
-values : std::map<qreal,uint16_t>
}
class "Ui_DialogArx" as C_0000516341418579579237
class C_0000516341418579579237 {
+retranslateUi(QDialog * DialogArx) : void
+setupUi(QDialog * DialogArx) : void
__
+buttonBox : QDialogButtonBox *
+chart_zaklocenia_view : QVBoxLayout *
+dodaj_wspolczynnik : QPushButton *
+doubleSpinBox : QDoubleSpinBox *
+doubleSpinBox_10 : QDoubleSpinBox *
+doubleSpinBox_2 : QDoubleSpinBox *
+doubleSpinBox_3 : QDoubleSpinBox *
+doubleSpinBox_4 : QDoubleSpinBox *
+doubleSpinBox_9 : QDoubleSpinBox *
+groupBox : QGroupBox *
+groupBox_2 : QGroupBox *
+groupBox_3 : QGroupBox *
+horizontalLayout : QHBoxLayout *
+horizontalLayoutWidget : QWidget *
+horizontalLayoutWidget_2 : QWidget *
+horizontalLayoutWidget_3 : QWidget *
+horizontalLayout_2 : QHBoxLayout *
+horizontalLayout_3 : QHBoxLayout *
+horizontalSlider_2 : QSlider *
+horizontalSlider_4 : QSlider *
+horizontalSlider_5 : QSlider *
+horizontalSlider_7 : QSlider *
+horizontalSlider_8 : QSlider *
+horizontalSpacer : QSpacerItem *
+horizontalSpacer_2 : QSpacerItem *
+horizontalSpacer_3 : QSpacerItem *
+label : QLabel *
+label_10 : QLabel *
+label_11 : QLabel *
+label_12 : QLabel *
+label_13 : QLabel *
+label_2 : QLabel *
+label_3 : QLabel *
+label_4 : QLabel *
+label_5 : QLabel *
+label_6 : QLabel *
+label_7 : QLabel *
+label_8 : QLabel *
+label_9 : QLabel *
+listView : QListView *
+ograniczenie_wej_max : QDoubleSpinBox *
+ograniczenie_wej_min : QDoubleSpinBox *
+ograniczenie_wyj_max : QDoubleSpinBox *
+ograniczenie_wyj_min : QDoubleSpinBox *
+opoznienie_suwak : QSlider *
+opoznienie_wartosc : QSpinBox *
+scrollArea : QScrollArea *
+scrollAreaWidgetContents : QWidget *
+slider : QSlider *
+usun_wspolczynnik : QPushButton *
+verticalLayoutWidget : QWidget *
+zaklocenie_suwak : QSlider *
+zaklocenie_wartosc : QSpinBox *
}
C_0000332654898198268485 o-- C_0003544794305486865442 : -integration_type
C_0003871390626336603026 ..> C_0016418138640912755596
C_0002626979548338364165 ..> C_0014553804139211016925
C_0015873013232297291266 <|-- C_0006611994892758867615
C_0018043015608687228134 o-- C_0001104664960286800752 : -a
C_0018043015608687228134 o-- C_0001104664960286800752 : -b
C_0018043015608687228134 o-- C_0005615096916452297607 : -y_i
C_0018043015608687228134 o-- C_0005615096916452297607 : -u_i
C_0018043015608687228134 o-- C_0016436472329008043786 : -output_limits
C_0018043015608687228134 o-- C_0016436472329008043786 : -input_limits
C_0018043015608687228134 <.. C_0002626979548338364165 : +<<friend>>
C_0007070034700002168771 ..> C_0016418138640912755596
C_0007070034700002168771 o-- C_0018043015608687228134 : -arx
C_0007070034700002168771 o-- C_0000332654898198268485 : -pid
C_0008416453855301937033 <|-- C_0005461363864585996070
C_0000516341418579579237 <|-- C_0001241395230117963560
C_0002900986228388971956 ..> C_0016418138640912755596
C_0002900986228388971956 --> C_0005461363864585996070 : -ui
C_0002900986228388971956 --> C_0005180472283857981683 : -lista_wartosc_zadana
C_0002900986228388971956 --> C_0005180472283857981683 : -lista_wartosc_regulowana
C_0002900986228388971956 --> C_0005180472283857981683 : -lista_uchyb
C_0002900986228388971956 --> C_0005180472283857981683 : -lista_sterowanie
C_0013559316693802428772 --+ C_0002900986228388971956
C_0015873013232297291266 <|-- C_0002207342585688024720
C_0012548033600169640822 ..> C_0016418138640912755596
C_0012548033600169640822 ..> C_0003544794305486865442
C_0012548033600169640822 ..> C_0001104664960286800752
C_0012548033600169640822 ..> C_0016436472329008043786
C_0012548033600169640822 o-- C_0007070034700002168771 : -uar
C_0012548033600169640822 o-- C_0006611994892758867615 : -gen_sin
C_0012548033600169640822 o-- C_0002207342585688024720 : -gen_pros
C_0012548033600169640822 o-- C_0011773683672513422965 : -choosen_type
C_0012548033600169640822 o-- C_0003871390626336603026 : -tick_callback
C_0009647332571105013514 --+ C_0012548033600169640822
C_0011773683672513422965 --+ C_0012548033600169640822
C_0004934292542202437282 --> C_0001241395230117963560 : -ui
C_0018037893356612265046 --+ C_0004934292542202437282
C_0009968107519566864188 o-- C_0005180472283857981683 : -list
C_0009968107519566864188 o-- C_0001997022298513289013 : -values

'Generated with clang-uml, version 0.6.2
'LLVM version clang version 20.1.7 (https://github.com/llvm/llvm-project.git 6146a88f60492b520a36f8f8f3231e15f3cc6082)
@enduml
